# This file was generated by GoReleaser. DO NOT EDIT.
class C2go < Formula
  desc ""
  homepage "https://github.com/ch1aki/c2go"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ch1aki/c2go/releases/download/v0.2.1/c2go_0.2.1_Darwin_x86_64.tar.gz"
    sha256 "ee6a7cc927795c1829c5c1dce9391d712e589605e7f30a16d565df7487ebce74"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ch1aki/c2go/releases/download/v0.2.1/c2go_0.2.1_Linux_x86_64.tar.gz"
      sha256 "53bf1b8a10d180b81ad54a66a1270da15b64263469595c9953b00d9464502045"
    end
  end

  def install
    bin.install "c2go"
  end
end
